### ISSUE TITLE
关于UNIMO预训练样本格式的问题

### ISSUE THREAD

**Issue by JianWenJun** [PaddlePaddle/Research#188]
您好，想请教2个问题：
1）同一个具体的text-image pair样本，在预训练的时候，是否同时会用该样本来计算CMCL损失和MRM/MLM损失？
2）如果第一个问题的结果为是的话，那对于这个具体的text-image pair样本，在做CMCL任务时是不是也含有mask字符或者mask roI？这样的话，整个模型在联合预训练的时候不会出现标签泄露的问题吗？
非常感谢~

**Comment by TriLoo** [comment]
同问啊
