### ISSUE TITLE
Text2SQL-BASELINE验证集上的acc超过1

### ISSUE THREAD

**Issue by Xuanfang1121** [PaddlePaddle/Research#216]
在paddle 2.1.3上运行text2sql-baseline代码，数据集为dusql，验证集上的结果超过1，这个是怎么回事？在paddle 2.0上运行代码会报错
下面是验证集上结果：
[eval] dev loss 0.000000, acc 6.0000. got best and saved. cost [4.41s]
[eval] dev loss 0.000000, acc 7.0000. got best and saved. cost [4.21s]
[eval] dev loss 0.000000, acc 8.0000. got best and saved. cost [1321.91s]

**Comment by ThisIsSoMe** [comment]
这上面acc并不是指真正的准确率，数值等于训练的轮次，准确率需要通过预测再评估的方式计算。

**Comment by Xuanfang1121** [comment]
收到，谢谢
