### ISSUE TITLE
Text2SQL-BASELINE 多卡训练报错

### ISSUE THREAD

**Issue by Xuanfang1121** [PaddlePaddle/Research#220]
最近text2sql-baseline 代码采用多卡进行训练，数据集为nl2sql，在conf/text2sql_nl2sql.jsonnet中的use_data_parallel 设置为true。代码报错如下：
![4088288C-85B9-41b6-92B6-52AA37476B5A](https://user-images.githubusercontent.com/33194029/141733942-d4765e5b-70b8-4941-a3f7-7ba9170c2c00.png)
环境配置如下：
paddle-ernie==0.2.0.dev1，
paddlenlp==2.1.0，
paddlepaddle-gpu==2.1.3.post112， 
CUDA的版本为11.2，显卡为2080Ti 和3080Ti
python的版本为3.7.9
这个报错如何处理？

**Comment by ThisIsSoMe** [comment]
你好！暂不支持多卡训练：）

**Comment by Xuanfang1121** [comment]
嗯嗯，谢谢
