### ISSUE TITLE
why are some tokens missed in the decoded output of Graphsum?

### ISSUE THREAD

**Issue by muguruzawang** [PaddlePaddle/Research#255]
Hi, I trained graphsum on new mult-document summarization for comparision. But when I do  testing ,I find some tokens are missing in the output, like this "" n " exical " unctional " rammars". 
It seems that the first token is not decoded. So I guess it may be cause by sentencepiece tokenizer. So I wonder what's the special format of the raw input?

Thanks. @Weili-NLP

**Comment by muguruzawang** [comment]
I solved it.

**Comment by isaacisaactang** [comment]
@muguruzawang How did you solve it?
