### ISSUE TITLE
errors running DuReader-Robust-BASELINE

### ISSUE THREAD

**Issue by wuhenbai** [PaddlePaddle/Research#38]
W0414 16:45:31.025034 10900 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.0, Runtime API Version: 9.0
W0414 16:45:31.028314 10900 device_context.cc:245] device: 0, cuDNN Version: 7.6.

I0414 16:45:33.431712 10900 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 2 cards are used, so 2 programs are executed in parallel.
W0414 16:45:36.668439 10900 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0414 16:45:36.668462 10900 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0414 16:45:36.668467 10900 init.cc:214] The detail failure signal is:

W0414 16:45:36.668470 10900 init.cc:217] *** Aborted at 1586853936 (unix time) try "date -d @1586853936" if you are using GNU date ***
W0414 16:45:36.670137 10900 init.cc:217] PC: @                0x0 (unknown)
W0414 16:45:36.670218 10900 init.cc:217] *** SIGSEGV (@0x0) received by PID 10900 (TID 0x7f7fa99b1700) from PID 0; stack trace: ***
W0414 16:45:36.671615 10900 init.cc:217]     @     0x7f7fa959d390 (unknown)
W0414 16:45:36.673030 10900 init.cc:217]     @                0x0 (unknown)

**Comment by HongyuLi2018** [comment]
”You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle“:  It seems a thread is killed  accidentally. Are you able to reproduce the error on the same environment?
