### ISSUE TITLE
在AI Studio上新建项目运行报错

### ISSUE THREAD

**Issue by JBoRu** [PaddlePaddle/Research#40]
你好，
  我在AI Studio上新建项目后，运行时出现错误：
![image](https://user-images.githubusercontent.com/38073482/79349113-771df600-7f68-11ea-8384-07d0add5550d.png)
python=3.7
PaddlePaddle=1.6.0
请问如何解决，谢谢！

**Comment by sserdoubleh** [comment]
已解决
