### ISSUE TITLE
ACL2019_DuConv generative_paddle loss error

### ISSUE THREAD

**Issue by julielin123** [PaddlePaddle/Research#58]
Hi,
I want to run the model in generative_paddle, but there is an error when I run run_train.sh:
`AssertionError: The loss.shape should be (1L,), but the current loss.shape is (-1L,). Maybe that you should call fluid.layers.mean to process the current loss.
`
How can I solve it? THANKS!

**Comment by yaolinli** [comment]
> Hi,
> I want to run the model in generative_paddle, but there is an error when I run run_train.sh:
> `AssertionError: The loss.shape should be (1L,), but the current loss.shape is (-1L,). Maybe that you should call fluid.layers.mean to process the current loss. `
> How can I solve it? THANKS!

Have you solve the problem?
