### ISSUE TITLE
Might be a bug

### ISSUE THREAD

**Issue by freesunshine0316** [PaddlePaddle/Research#89]
https://github.com/PaddlePaddle/Research/blob/b466c223b5b718588384460c470ffcf086559cfe/NLP/Dialogue-PLATO/plato/metrics/metrics.py#L32

Is
```
zip(seq, seq[1:])
```
suppose to be
```
zip(seq[:-1], seq[1:])
```

**Comment by sserdoubleh** [comment]
This is not a bug. It is equivalent.
```
>>> x = list(range(10))
>>> print(list(zip(x, x[1:])))
[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9)]
```
