### ISSUE TITLE
I think parallel.py in PLATO implementation raises attribute error

### ISSUE THREAD

**Issue by rokslej** [PaddlePaddle/Research#92]
Hello, 
It might be a silly question because it's my first time using paddle based codes... I hope your understanding!

I'm trying to run PLATO fine-tuning code, and I met 'Parameter' object has no attribute '_grad_ivar' error' at apply_collectice_grads function in parallel.py in plato implementation.

I also noticed that this function is also implemented in paddle/fluid/dygraph/parallel.py, and it was slightly different from the implementation in plato.

Therefore, I changed the function in plato just like the function in paddle implementaion.
As a result, I can run this code, but I still don't know if this method will make sense... I need your help!!

Thank you.

<pre>
<code>
        for param in self._layers.parameters():
            # NOTE(zcd): The grad_ivar maybe no generated.
            #if param.trainable and param._grad_ivar():
            if param.trainable and param._ivar._grad_ivar():
                g_var = param._grad_ivar()
                grad_vars.append(g_var)
                assert g_var not in grad_var_set
                grad_var_set.add(g_var)
</code>
</pre>
at apply_collectice_grads function in Research/NLP/Dialogue-PLATO/plato/modules/parallel.py
<pre>
<code>
        for param in self._layers.parameters():
            # NOTE(zcd): The grad_ivar maybe no generated.
            if param.trainable and param._ivar._grad_ivar():
                g_var = framework.Variable(
                    block=self._helper.main_program.current_block(),
                    name=param._ivar._grad_name(),
                    stop_gradient=True,
                    ivar=param._ivar._grad_ivar())
                grad_vars.append(g_var)
                assert g_var not in grad_var_set
                grad_var_set.add(g_var)
</code>
</pre>
at apply_collectice_grads function in paddle/fluid/dygraph/parallel.py

**Comment by sserdoubleh** [comment]
You can run the code on paddlepaddle 1.6 normally(such as `paddlepaddle-gpu==1.6.1.post107`).

**Comment by sserdoubleh** [comment]
Fix it!
https://github.com/PaddlePaddle/Research/pull/93

**Comment by rokslej** [comment]
Thank you for your quick feedback!!! :)
